apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: java
        image: abhi755/practise:java-v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
